### ISSUE TITLE
[BUG] Does not detect bun

### ISSUE THREAD

**Issue by octoshrimpy** [nuejs/create-nue#7] opened 2023-09-15 15:42 UTC
using bun to run, it still says "no builder found (esbuild or Bun)"
![image](https://github.com/nuejs/create-nue/assets/7097172/7ff66138-3dc3-4f8f-8d5a-7fb1a86c633f)

**Comment by kon-pas** [comment] 2023-09-22 17:04
Use the `--bun` flag, like so:
```bash
```

**Comment by kon-pas** [comment] 2023-09-22 17:25
Use the `--bun` flag, like so:
```bash
bun --bun start
```
This would be the whole Bun setup equivalent:
```bash
git clone https://github.com/nuejs/create-nue.git
cd create-nue
bun install
bun --bun start
open "http://localhost:8080"
```
This issue is caused by the Node shebang (`#!/usr/bin/env node`) in the script. Bun respects it and executes the script using Node. We have to explicitly override it, hence the `--bun` flag.

**Comment by tipiirai** [comment] 2023-10-09 05:14
Thank you @kon-pas for this!

**Comment by tipiirai** [comment] 2023-12-19 08:52
Closing this one, since this issue relates to the original/outdated version

**Closed by tipiirai** 2023-12-19 08:52 UTC
